### ISSUE TITLE
Other method for IAM enumeration

### ISSUE THREAD

**Issue by acarnage** [NetSPI/gcpwn#2]
Hello,

I am writing this issue to highlight a native GCP method for testing current user IAM permissions.

Basically, most, if not all, of the resources holding IAM policies (such as projects, functions, buckets, etc.) have a dedicated API endpoint that can be used to test if the currently authenticated user has permissions among a list of permissions you pass to that endpoint.

From my understanding, it is heavily used by the GCP console itself to determine whether to enable buttons in the UI.

You can find the official documentation [here](https://cloud.google.com/iam/docs/testing-permissions).

I think it can be a valuable module to add for IAM enumeration.

Note: From an attacking point of view and based on my tests, it seems that this method does not leave any logs on the GCP projects. Such enumeration would thus be discreet.

Regards,

**Comment by WebbinRoot** [comment]
Is this referring to the testIamPermissions endpoints? These are already implemented in all the current enumeration modules and can be run by adding the `--iam` flag to most enumeration modules (ex. `modules run enum_buckets --iam` will enumerate buckets AND call testIamPermissions for each bucket).

Projects/Folders/Orgs also have an exception where you can run the testIamPermissions API call as part of the enumeration and pass in ~9000 permissions with `--all-permissions` (ex.  `modules run enum_resources --iam --all-permissions` will enumerate folders/orgs/projects AND call testIamPermissions for each resource AND pass in ~9000 permissions as opposed to a smaller default set)

I show how to use this flag briefly at around 8:00 here: https://www.youtube.com/watch?v=opvv9h3Qe0s

GCPwn at this point in time supports testIamPermissions API calls for 

1. Organizations
2. Folders
3. Projects
4. Buckets
5. Compute Instances
6. Cloud Functions
7. Service Accounts

To run ALL testIAMPermissions API calls, you can also add the flag to `enum_all` (ex. `modules run enum_all --iam` will run ALL enumeration modules AND call testIamPermissions where applicable) and then run `creds info` or `creds info --csv` afterwards (like in the video above) to see the output and save it to a CSV in the GatheredData folder.

Note this will all be detailed in a wiki I am going to release early next week for this GitHub Repository :)

**Comment by WebbinRoot** [comment]
Closing this issue as feature is already in tool as seen above.
